# Generated by Django 4.2.4 on 2023-08-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                ("station_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("lat", models.FloatField()),
                ("long", models.FloatField()),
            ],
            options={
                "ordering": ["station_id"],
            },
        ),
    ]
