# Generated by Django 4.2.4 on 2023-09-12 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "service_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("monday", models.BooleanField(default=False)),
                ("tuesday", models.BooleanField(default=False)),
                ("wednesday", models.BooleanField(default=False)),
                ("thursday", models.BooleanField(default=False)),
                ("friday", models.BooleanField(default=False)),
                ("saturday", models.BooleanField(default=False)),
                ("sunday", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["service_id"],
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "route_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("capacity", models.IntegerField(null=True)),
            ],
            options={
                "ordering": ["route_id"],
            },
        ),
        migrations.CreateModel(
            name="Shape",
            fields=[
                (
                    "shape_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("shape_pt_lat", models.FloatField()),
                ("shape_pt_lon", models.FloatField()),
                ("shape_pt_sequence", models.IntegerField()),
            ],
            options={
                "ordering": ["shape_id", "shape_pt_sequence"],
            },
        ),
        migrations.CreateModel(
            name="SimulationOutput",
            fields=[
                (
                    "simulation_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "station_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("station_code", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("lat", models.FloatField()),
                ("long", models.FloatField()),
                ("location_type", models.IntegerField()),
            ],
            options={
                "ordering": ["station_id"],
            },
        ),
        migrations.CreateModel(
            name="TravelTimes",
            fields=[
                (
                    "traveltime_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("duration", models.FloatField(default=0)),
                (
                    "from_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_station",
                        to="db.station",
                    ),
                ),
                (
                    "to_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_station",
                        to="db.station",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Timetable",
            fields=[
                (
                    "trip_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("arrival_time", models.TimeField(max_length=255)),
                ("sequence", models.IntegerField()),
                (
                    "station",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.station",
                    ),
                ),
            ],
            options={
                "ordering": ["trip_id"],
                "unique_together": {("trip_id", "station")},
            },
        ),
    ]
