# Generated by Django 4.2.4 on 2023-10-10 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="itinerarysim",
            unique_together=set(),
        ),
    ]
