# Generated by Django 4.2.4 on 2023-08-29 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                ("route_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("station_sequence", models.IntegerField()),
                (
                    "end",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="end",
                        to="db.station",
                    ),
                ),
                (
                    "start",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="start",
                        to="db.station",
                    ),
                ),
            ],
            options={
                "ordering": ["route_id"],
            },
        ),
        migrations.CreateModel(
            name="Timetable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arrival_times", models.CharField(max_length=255)),
                (
                    "route_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="db.route"
                    ),
                ),
                (
                    "station_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="db.station"
                    ),
                ),
            ],
            options={
                "ordering": ["station_id", "route_id"],
                "unique_together": {("station_id", "route_id")},
            },
        ),
    ]
