# Generated by Django 4.2.4 on 2023-09-12 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="timetable",
            unique_together={("trip_id", "station", "arrival_time", "sequence")},
        ),
    ]
