# Generated by Django 4.2.4 on 2023-09-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="route_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
