# Generated by Django 4.2.4 on 2023-09-05 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetable",
            name="station",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="db.station"
            ),
        ),
    ]
