# Generated by Django 4.2.4 on 2023-09-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_alter_timetable_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="suburb",
            field=models.CharField(default="TEMP", max_length=255),
            preserve_default=False,
        ),
    ]
