# Generated by Django 4.2.4 on 2023-09-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_alter_route_route_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="route_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
