# Generated by Django 4.2.4 on 2023-08-30 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_route_timetable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="end",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="end",
                to="db.station",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="start",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="start",
                to="db.station",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="station_sequence",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="route_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db.route"
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="station_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db.station"
            ),
        ),
    ]
