# Generated by Django 4.2.4 on 2023-08-30 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0003_alter_route_end_alter_route_start_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationOutput",
            fields=[
                (
                    "simulation_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="route",
            old_name="type",
            new_name="transport_type",
        ),
        migrations.AddField(
            model_name="route",
            name="next_st",
            field=models.ForeignKey(
                default=99999999999,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="next",
                to="db.station",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="prev_st",
            field=models.ForeignKey(
                default=99999999999,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prev",
                to="db.station",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="station_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name="route",
            unique_together={("route_id", "station_id")},
        ),
        migrations.RemoveField(
            model_name="route",
            name="end",
        ),
        migrations.RemoveField(
            model_name="route",
            name="start",
        ),
        migrations.RemoveField(
            model_name="route",
            name="station_sequence",
        ),
    ]
