# Generated by Django 4.2.4 on 2023-09-05 02:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0003_alter_route_route_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="stations",
        ),
    ]
