# Generated by Django 4.2.4 on 2023-08-30 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0004_simulationoutput_rename_type_route_transport_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="capacity",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="route",
            name="next_st",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="next",
                to="db.station",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="prev_st",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prev",
                to="db.station",
            ),
        ),
        migrations.CreateModel(
            name="TravelTimes",
            fields=[
                (
                    "traveltime_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("duration", models.FloatField(default=0)),
                (
                    "from_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_station",
                        to="db.station",
                    ),
                ),
                (
                    "to_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_station",
                        to="db.station",
                    ),
                ),
            ],
        ),
    ]
