# Generated by Django 4.2.4 on 2023-09-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0004_remove_route_stations"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="translink_trip_id_simple",
            field=models.IntegerField(default=999999),
            preserve_default=False,
        ),
    ]
