# Generated by Django 4.2.4 on 2023-09-05 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0005_trip_translink_trip_id_simple"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timetable",
            fields=[
                (
                    "timetable_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("translink_trip_id", models.CharField(max_length=255)),
                ("translink_trip_id_simple", models.IntegerField()),
                ("arrival_time", models.CharField(max_length=255)),
                ("sequence", models.IntegerField()),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.route"
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.station"
                    ),
                ),
            ],
            options={
                "ordering": ["timetable_id"],
            },
        ),
        migrations.DeleteModel(
            name="Trip",
        ),
    ]
